Issue 26
20-1-SKKU-OSS/c9-python-getting-started pull request #30
Opened 2020-06-06 09:32 UTC by Dorika0203

I've fixed indent for more-python-for-beginners/chap 1~3, issue of #26 
Also, I've wrote some additional examples in code.

2020-06-06 09:33 UTC, devquint requested changes
Do not change any of the code here, use another branch not under `indent-unify`.

2020-06-06 09:34 UTC, Dorika0203 commented
Oh, okay

2020-06-06 10:16 UTC, Dorika0203 commented
I've reset the commits before and added new commits. @devquint

2020-06-07 04:40 UTC, devquint requested changes
There's no other problem than I commented each file/line, check them please.

2020-06-07 04:40 UTC, devquint commented on more-python-for-beginners/01 - Formatting and linting/bad.py
> +    pass
I think `bad.py` should be indented badly, as original.

2020-06-07 04:40 UTC, devquint commented on more-python-for-beginners/02 - Lambdas/failed_sort.py
> +        {'name':'Susan', 'age':50},
Should be 1 level(4 spaces).

2020-06-07 04:40 UTC, devquint commented on more-python-for-beginners/02 - Lambdas/failed_sort.py
> +        {'name':'Christopher', 'age':47}
Should be 1 level(4 spaces).

2020-06-07 04:40 UTC, devquint commented on more-python-for-beginners/02 - Lambdas/failed_sort.py
> +        ]
Should be 0 level(0 spaces).

2020-06-07 04:40 UTC, devquint commented on more-python-for-beginners/02 - Lambdas/lambda_sorter.py
> +        ]
Same as above(`filed_sort.py`)

2020-06-07 04:40 UTC, devquint commented on more-python-for-beginners/02 - Lambdas/method_sorter.py
> +        ]
Same as above(`filed_sort.py`)

2020-06-07 18:53 UTC, Dorika0203 commented
@devquint Sorry about too much wrong indenting. I've found out the reason - using vim editor indenting caused this level problem. Thanks for your review.

2020-06-08 02:02 UTC, devquint approved these changes

2020-06-08 08:49 UTC, Hyuntae-Jeong approved these changes

2020-06-08 09:53 UTC, jesusleejy approved these changes

2020-06-09 04:15 UTC, merged