Unifying indentation: python-for-beginners/chapter 8-10
20-1-SKKU-OSS/c9-python-getting-started pull request #31
Opened 2020-06-06 10:39 UTC by jesusleejy

resolves #29

2020-06-06 13:15 UTC, Dorika0203 approved these changes
One commit is not related to the issue #29  - but I don't think that's quite a big problem.

2020-06-07 04:45 UTC, devquint requested changes
There's no other problem than I commented each file/line, check them please.

2020-06-07 04:45 UTC, devquint commented on python-for-beginners/08 - Handling conditions/code_challenge.py
> +    print('Tax rate is: ' + str(tax))
This is not in `else` block

2020-06-07 04:45 UTC, devquint commented on python-for-beginners/04 - String variables/format_strings.py
> +)
This changes should not be in this commit

2020-06-08 03:08 UTC, devquint requested changes
I checked your 8-`code_challenge.py `.
However reverting commit by `revert` might cause some unpredictable output when we finally merge branches.

2020-06-08 07:02 UTC, devquint requested changes
I found your rebasing worked well.
However I found one `\t` missing, please check it.

2020-06-08 07:02 UTC, devquint commented on python-for-beginners/09 - Handling multiple conditions/or_statements.py
>  	tax = 0.05
This still `\t`,
maybe make line 4 to 8 spaces and line 5 to 4 spaces would be good.

2020-06-08 08:49 UTC, devquint approved these changes

2020-06-08 11:39 UTC, Hyuntae-Jeong approved these changes

2020-06-09 04:15 UTC, merged