Unifying indentation: python-for-beginners/chapter 11-13
20-1-SKKU-OSS/c9-python-getting-started pull request #39
Opened 2020-06-06 14:27 UTC by ChaeyeonSeo

It resolves issue #37 .

2020-06-07 04:58 UTC, devquint requested changes
1. **Check each comments of file/line**

2. 13 - `get_initials.py`, **should** be deal with line 12, better to deal with line 11-12

3. 13 - `get_initails_function.py`, better to deal with line 24-25

4. 13 - `getting_clever_with_functions_harder_to_read.py`, better to deal with line 17-20

2020-06-07 04:58 UTC, devquint commented on python-for-beginners/13 - Functions/code_challenge_solution.py
> +# Should return 10#
What's the ending `#` means?

2020-06-07 04:58 UTC, devquint commented on python-for-beginners/13 - Functions/code_challenge_solution.py
> +
Do not handle with newline in this branch.

2020-06-07 04:58 UTC, devquint commented on python-for-beginners/13 - Functions/code_challenge_solution.py
> +
Do not handle with newline in this branch.

2020-06-07 04:58 UTC, devquint commented on python-for-beginners/13 - Functions/code_challenge_solution.py
> +
Do not handle with newline in this branch.

2020-06-07 04:58 UTC, devquint commented on python-for-beginners/13 - Functions/print_time_function_different_messages.py
> +
Do not handle with newline in this branch.

2020-06-07 04:58 UTC, devquint commented on python-for-beginners/13 - Functions/print_time_with_message_parameter.py
> +
Do not handle with newline in this branch.

2020-06-07 04:58 UTC, devquint commented on python-for-beginners/13 - Functions/print_time_with_message_parameter.py
> +
Do not handle with newline in this branch.

2020-06-07 04:58 UTC, devquint commented on python-for-beginners/13 - Functions/code_challenge_solution.py
> -
Do not handle with newline in this branch.

2020-06-07 04:58 UTC, devquint commented on python-for-beginners/13 - Functions/code_challenge_solution.py
> -#
Do not handle with trim comments in this branch.

2020-06-07 04:58 UTC, devquint commented on python-for-beginners/13 - Functions/code_challenge_solution.py
> -#
Do not handle with trim comments in this branch.

2020-06-08 03:26 UTC, devquint approved these changes

2020-06-08 06:44 UTC, Dorika0203 approved these changes

2020-06-08 09:04 UTC, Hyuntae-Jeong approved these changes

2020-06-08 09:55 UTC, jesusleejy approved these changes

2020-06-09 04:16 UTC, merged