Fix code challenge solution.py 1
20-1-SKKU-OSS/c9-python-getting-started pull request #4
Opened 2020-05-30 09:52 UTC by ChaeyeonSeo

2020-05-30 10:19 UTC, devquint requested changes
1. Test for ADD doesn't make sense

Line 18: comment says, passing in **only the numbers** 6 and 4
Line 21: passing some argument not number, `operation='add'`

I think you can add one more test that testing with `operation='add'`, or just removing this operation argument at line 21.


2. Dividing test should pass argument `divide` or so on.

For testing invalid notation, you should give an argument `operation` as neither `add` or `subtract` to get some error message for the given solution code. 
However you give the `operation` argument just not fit to the condition described by the comment(line 28, 29), so this code is not fit to test error message.

=====

If the above issues are solved, I agree to your changing name and adding more situations.

2020-05-31 05:50 UTC, ChaeyeonSeo commented
Thanks for reviewing, and I solved those issues now.

2020-05-31 10:36 UTC, devquint approved these changes

2020-06-05 06:27 UTC, Dorika0203 commented
I think this bonus problem is quite good. Let me merge this one.

2020-06-05 06:27 UTC, merged