Unifying indentation: python-for-beginners/chapter 17-18
20-1-SKKU-OSS/c9-python-getting-started pull request #43
Opened 2020-06-07 06:58 UTC by Hyuntae-Jeong

resolves issue #42

2020-06-07 18:28 UTC, Dorika0203 approved these changes

2020-06-08 02:12 UTC, devquint requested changes
To look this issue(I commented) as indent or not would be varying by people, so you could ignore this `request changes`.

There's no other problem than I commented each file/line, just check them and determine fix or not please.

2020-06-08 02:12 UTC, devquint commented on python-for-beginners/17 - JSON/read_json.py
> +headers    = {
`headers = {` 
This might related to indent(maybe some align), fixing or not is on your own.

2020-06-08 02:12 UTC, devquint commented on python-for-beginners/17 - JSON/read_json.py
> +parameters  = {
`parameters = {` 
This might related to indent(maybe some align), fixing or not is on your own.

2020-06-08 02:12 UTC, devquint commented on python-for-beginners/17 - JSON/read_key_pair.py
> +parameters  = {
same as `read_json.py`

2020-06-08 02:12 UTC, devquint commented on python-for-beginners/17 - JSON/read_key_pair.py
> +headers    = {
same as `read_json.py`

2020-06-08 02:12 UTC, devquint commented on python-for-beginners/17 - JSON/read_key_pair_list.py
> +parameters  = {
same as `read_json.py`

2020-06-08 02:12 UTC, devquint commented on python-for-beginners/17 - JSON/read_key_pair_list.py
> +headers    = {
same as `read_json.py`

2020-06-08 02:12 UTC, devquint commented on python-for-beginners/17 - JSON/read_subkey.py
> +parameters  = {
same as `read_json.py`

2020-06-08 02:12 UTC, devquint commented on python-for-beginners/17 - JSON/read_subkey.py
> +headers    = {
same as `read_json.py`

2020-06-08 02:13 UTC, devquint commented
If you think this is not indentation problem and wanna keep this, just tell me and I'll change to apporve.

2020-06-08 02:20 UTC, Hyuntae-Jeong commented
@devquint I will keep it! I appreciate your review

2020-06-08 02:20 UTC, devquint approved these changes

2020-06-08 11:20 UTC, jesusleejy approved these changes

2020-06-09 04:16 UTC, merged